name: sailing_rules
description: sailing_rules_2021_2024
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.8+1

environment:
  sdk: '>=3.1.5 <4.0.0'


  # dependencies: This section is used to declare the packages that are required for the Flutter
  # application to run in a production environment.
  # The packages listed under dependencies are essential for the normal
  # operation of the application and are installed when someone uses the package or app.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  go_router: ^13.0.0
  url_launcher: ^6.2.1
  package_info_plus: ^5.0.1
  auto_size_text: ^3.0.0
  styled_text: ^8.1.0
  permission_handler: ^11.1.0
  package_info: ^2.0.2
  # dev_dependencies: This section is used to declare packages that are only needed during development,
  # testing, or building processes but are not required for the actual execution of the application.
  # These dependencies are not included when the app is compiled and packaged for distribution.
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ocean_background.png
    - assets/json_data_files/part_one_fundamental_rules.json
    - assets/json_data_files/part_two_section_a_when_boats_meet.json
    - assets/json_data_files/part_two_section_b_when_boats_meet.json
    - assets/json_data_files/part_two_section_c_when_boats_meet.json
    - assets/json_data_files/part_two_section_d_when_boats_meet.json
    - assets/json_data_files/part_three_conduct_of_race.json
    - assets/json_data_files/part_four_section_a_other_requirements.json
    - assets/json_data_files/part_four_section_b_other_requirements.json
    - assets/json_data_files/part_five_section_a_protests.json
    - assets/json_data_files/part_five_section_b_protests.json
    - assets/json_data_files/part_five_section_c_protests.json
    - assets/json_data_files/part_five_section_d_protests.json
    - assets/json_data_files/part_six_entry.json
    - assets/json_data_files/part_seven_race.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
