class SelectionsModel {
  final selectionNames = <String>[
    'PART 1 FUNDAMENTAL RULES',
    'PART 2 WHEN BOATS MEET',
    'PART 3 CONDUCT OF A RACE',
    'PART 4 OTHER REQUIREMENTS WHEN RACING',
    'PART 5 PROTESTS, REDRESS, HEARINGS, MISCONDUCT AND APPEALS',
    'PART 6 ENTRY AND QUALIFICATION',
    'PART 7 RACE ORGANIZATION',
  ];
  final partTwoSelectionNames = <String>[
    'SECTION A RIGHT OF WAY',
    'SECTION B GENERAL LIMITATIONS',
    'SECTION C AT MARKS AND OBSTRUCTIONS',
    'SECTION D OTHER RULES',
  ];

  final partFourSelectionNames = <String>[
    'SECTION A GENERAL REQUIREMENTS',
    'SECTION B EQUIPMENT-RELATED REQUIREMENTS',
  ];

  final partFiveSelectionNames = <String>[
    'SECTION A PROTESTS; REDRESS; RULE 69 ACTION',
    'SECTION B HEARINGS AND DECISIONS',
    'SECTION C MISCONDUCT',
    'SECTION D APPEALS',
  ];
}
