class SelectionsModel {
  final selectionPartNames = <String>[
    'PART 1 FUNDAMENTAL RULES',
    'PART 2 WHEN BOATS MEET\nSECTION A RIGHT OF WAY',
    'PART 2 WHEN BOATS MEET\nSECTION B GENERAL LIMITATIONS',
    'PART 2 WHEN BOATS MEET\nSECTION C AT MARKS AND OBSTRUCTIONS',
    'PART 2 WHEN BOATS MEET\nSECTION D OTHER RULES',
    'PART 3 CONDUCT OF A RACE',
    'PART 4 OTHER REQUIREMENTS WHEN RACING\nSECTION A GENERAL REQUIREMENTS',
    'PART 4 OTHER REQUIREMENTS WHEN RACING\nSECTION B EQUIPMENT-RELATED REQUIREMENTS',
    'PART 5 PROTESTS/REDRESS/HEARINGS/MISCONDUCT & APPEALS\nSECTION A PROTESTS; REDRESS; RULE 69 ACTION',
    'PART 5 PROTESTS/REDRESS/HEARINGS/MISCONDUCT & APPEALS\nSECTION B HEARINGS AND DECISIONS',
    'PART 5 PROTESTS/REDRESS/HEARINGS/MISCONDUCT & APPEALS\nSECTION C MISCONDUCT',
    'PART 5 PROTESTS/REDRESS/HEARINGS/MISCONDUCT & APPEALS\nSECTION D APPEALS',
    'PART 6 ENTRY AND QUALIFICATION',
    'PART 7 RACE ORGANIZATION',
  ];

  final partOneSelectionNames = <String>[
    '1 SAFETY',
    '2 FAIR SAILING',
    '3 DECISION TO RACE',
    '4 ACCEPTANCE OF THE RULES',
    '5 RULES GOVERNING ORGANIZING AUTHORITIES AND OFFICIALS',
    '6 WORLD SAILING REGULATIONS',
  ];

  final partTwoSelectionNames = <String>[
    'SECTION A RIGHT OF WAY',
    'SECTION B GENERAL LIMITATIONS',
    'SECTION C AT MARKS AND OBSTRUCTIONS',
    'SECTION D OTHER RULES',
  ];

  final partFourSelectionNames = <String>[
    'SECTION A GENERAL REQUIREMENTS',
    'SECTION B EQUIPMENT-RELATED REQUIREMENTS',
  ];

  final partFiveSelectionNames = <String>[
    'SECTION A PROTESTS; REDRESS; RULE 69 ACTION',
    'SECTION B HEARINGS AND DECISIONS',
    'SECTION C MISCONDUCT',
    'SECTION D APPEALS',
  ];
}
